after hard work with Mirco and Philipp we came up with some changes i…
ecmwf/multio pull request #18
Opened 2023-09-20 14:11 UTC by dsidoren

…n GribEncoder which are required to run with FESOM

2023-09-20 14:11 UTC, FussyDuck commented
[![CLA assistant check](https://bol-claassistant.ecmwf.int:443/pull/badge/not_signed)](https://bol-claassistant.ecmwf.int:443/ecmwf/multio?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/multio?pullRequest=18) before we can accept your contribution.<br/><hr/>**Dmitry Sidorenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/multio?pullRequest=18) it.</sub>

2023-09-22 10:29 UTC, dsarmany requested changes
I'm glad you've managed to get it work!

It would be even nicer if you could come up with some names for gridType and gridSubtype for the FESOM grids you may want to use and put it in the definition tables. Now that data governance have made the the heavy lifting of creating the framework, it is not much of an effort.

2023-09-22 10:29 UTC, dsarmany commented on src/multio/action/encode/GribEncoder.cc
> +    if ( config_.has("grid-type") ){
We could also have the one-liner:
```c++
setValue("unstructuredGridType", config_.getString("grid-type", "undefined"));
```
That would set `grid-type` to `undefined` automatically if that key is not found in the configuration.

2023-09-22 10:29 UTC, dsarmany commented on src/multio/action/encode/GribEncoder.cc
> +    if ( config_.has("grid-type") ){
We could also have the one-liner:
```c++
setValue("unstructuredGridType", config_.getString("grid-type", "undefined"));
```
That would set `grid-type` to `undefined` automatically if that key is not found in the configuration.

2023-09-22 10:29 UTC, dsarmany commented on src/multio/action/encode/GribEncoder.cc
> +     const auto& gridSubtype = metadata.getString("gridSubtype");
Similarly:
```c++
setValue("unstructuredGridSubtype", config_.getString("gridSubtype", "undefined")); // Or just "F" if "undefined" does not work
```

2023-09-22 10:29 UTC, dsarmany commented on src/multio/action/encode/GribEncoder.cc
> +    if ( metadata.has("uuidOfHGrid") ){
And here:
```c++
setValue("uuidOfHGrid", config_.getString("uuidOfHGrid", "00000000000000000000000000000000"));
```

2024-03-01 10:16 UTC, geier1993 commented
@dsarmany I think we can close this now.

2024-03-02 21:47 UTC, closed without merging

2024-03-02 21:48 UTC, dsarmany commented
Close it as the it has been resolved in a slightly different branch/way.